### ISSUE TITLE
SearchResults using ViewComponents

### ISSUE THREAD

**Issue by poornimanayar** [skttl/umbraco-fulltextsearch8#108]
Hi 

I tried using [this demo code ](https://github.com/skttl/umbraco-fulltextsearch8/blob/master/docs/developers-guide-v2.md#the-clean-way) in a ViewComponent and it is not returning me any result.

![image](https://github.com/skttl/umbraco-fulltextsearch8/assets/3941753/95e79181-a5fe-4609-95da-29c4184f3de6)

I tried using the exact same code in a View, injecting the `FullTextSearchHelper` and it works well. 

![image](https://github.com/skttl/umbraco-fulltextsearch8/assets/3941753/f40fde0f-1e0a-4e48-b88a-8f1237686217)

Anything I am doing wrong?

Poornima

**Comment by skttl** [comment]
Hi Poornima, thanks for trying out my package :)

The second parameter of `_searchService.Search()` is for specifying which page of the search results you want, but you've put in the id of a published content. That could be why, although I'm not really sure what happens if you put in a pagenumber, that won't exist.

Also, the way you get you search terms from the querystring differs. Not sure if that means anything :)

**Comment by poornimanayar** [comment]
Hi Soren, 

That might be why! Let me see. I mistook the demo code completely! 

I love this package. I have used it in v7. 

Poornima

**Comment by poornimanayar** [comment]
Yup! That was it! I mistook the current page to be the page in Umbraco. I should shut down my computer given my brain is not working! haha

The package is great Soren! No two ways about it :-)
