### ISSUE TITLE
Enumerate the search results

### ISSUE THREAD

**Issue by stefankip** [skttl/umbraco-fulltextsearch8#54]
About this line: https://github.com/skttl/umbraco-fulltextsearch8/blob/7b32850ba662bcaeeea6aba04da38eacad8b59e7/src/Our.Umbraco.FullTextSearch/Services/SearchService.cs#L49
I would add a `ToList()` at the end, so the collection gets enumerated and this prevents multiple enumerations of the same collection.

**Comment by skttl** [comment]
Is it getting enumerated further in Full Text Search code? Or is it when you implement the package?

**Comment by stefankip** [comment]
In my implementation. I accessed the `Results` also for displaying the count, instead of using the `TotalResults` property (which I use now).
So in my case the `Results` were enumerated 3 times, instead of just once. It's an easy fix to prevent this from happening imo and I can't think of a downside, but maybe you have one?

**Comment by skttl** [comment]
Couldn't there be a potential memory issue if the enumeration is done too early?

I admit, this is something I don't have any expertise in, so any advice is welcome :)

**Comment by kipusoep** [comment]
I don't see how this can lead to a memory issue. It just makes sure the enumeration is done once, which I think is good in this case.
But as I said I might miss something ;-)

**Comment by skttl** [comment]
But doesn't that load the whole list of results into memory? (basing on this https://stackoverflow.com/questions/3628425/ienumerable-vs-list-what-to-use-how-do-they-work)

Again - no expertise :)

**Comment by stefankip** [comment]
AFAIK it's this:

> Whenever I'm "stacking" LINQ expressions, I use IEnumerable, because by only specifying the behavior I give LINQ a chance to defer evaluation and possibly optimize the program.

Versus:

> So is it faster to use List over IEnumerable? Only if you want to prevent a query from being executed more than once.

When doing DB work one should always use `IEnumerable`, until all LINQ queries are applied and the result is complete.
In the end, when one iterates an IEnumerable, the same amount of memory is used.

This quote is nice imo:
> There are pros and cons to both. If you call ToList, you may remove some mystery as to when the query gets executed. If you stick to IEnumerable, you get the advantage that the program doesn't do any work until it's actually required.

**Comment by Shazwazza** [comment]
> But doesn't that load the whole list of results into memory?

Yes but your search results shouldn't be 1000000s of results, they should always be limited to a max... and better yet paged.

IEnumerable is an implementation, it's not the same everywhere. The IEnumerable on ISearchResult in Examine is  a custom enumerator. Once you start enumerating it, that's when the search will be executed. Same thing with the built-in Skip. 

Rules:

* Don't re-enumerate an IEnumerable
  * This is easy to accidentally do with all linq things like .Any(), .Count(), .First(), .Last(), Single() etc... all of these re-iterate. Count, Last, Single are especially bad since they enumerate the entire collection from start to end. This ok if you are only enumerating the collection **once**
* If you need to iterate more than once, resolve it into a List<T>. Yes this is stored in memory but that is much faster than the alternative and memory gets cleared ... so long as you're not pinning this to a static reference. The search result set shouldn't be huge (but that means it should be limited!)
* Don't use Linq when there are much better options available. When you have a real ICollection like List, array, etc... these already have .Count, .Length properties = use them. Don't rely on Linq .Any() for things this is huge overhead

All of these rules apply to using IPublishedContent. This is the biggest problem in sites is too much enumeration and using Linq across collections a ton of times over and over again. I've seen some razor pages that re-iterate an IEnumerable in IPublishedContent 10-100s of thousands of times on each request 😱  that's due to using .Count(), .Any() all over the place without understanding what it does.

**Comment by skttl** [comment]
Cool - thanks for elaborating @Shazwazza!

**Comment by skttl** [comment]
@stefankip I guess the ToList() should come before `Select(GetFullTextSearchResultItem)`, right?

**Comment by stefankip** [comment]
It should be the last thing you do, I think. So after the Select call.

**Comment by skttl** [comment]
Yeah, but as @Shazwazza writes

> IEnumerable is an implementation, it's not the same everywhere. The IEnumerable on ISearchResult in Examine is a custom enumerator. Once you start enumerating it, that's when the search will be executed. Same thing with the built-in Skip.

Wouldn't it execute the search both on `Skip` and `Select`?

**Comment by stefankip** [comment]
AFAIK `Skip` and `Select` only adds an instruction to the `IEnumerable` and doesn't materialize it, hence it returning another `IEnumerable`. The call to `ToList` at the end would be the only thing materializing the `IEnumerable`.
But I might be wrong here 😏

**Comment by Shazwazza** [comment]
Correct 👍
