### ISSUE TITLE
Summary is not always set

### ISSUE THREAD

**Issue by Nikkelmann** [skttl/umbraco-fulltextsearch8#75]
Even when there is a FullTextContent field in the index, the summary is seemingly only added if the highlighter matches words within the first line or so.
There also seems to be no way to force the summary to always be shown when there are no matching words; currently it will only show the summary if the content length is less than or equal to the summary length setting.
https://github.com/skttl/umbraco-fulltextsearch8/blob/ed35909b9107916167f91d841ad9f7815e6f4abd/src/Our.Umbraco.FullTextSearch/Services/SearchService.cs#L357-L364

I tried replacing the new lines in the Highlighter.FindSnippet method `var sentences = text.Replace('\n', ' ').Split('.');` and this returns the matches in the summary, though I'm not sure if this is the correct approach.

In the following test case it will not match the word "condimentum" nor anything after it:
```c#
void Main()
{
	var input = @"
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut justo turpis, faucibus vel pharetra et, viverra et ex. Suspendisse sagittis sodales nisl ac condimentum
Efficitur (PDF)
5/25/2020
Donec sit amet odio
Recurring (PDF)";

	var highlightSearchTerms = true;
	var summary = Highlighter.FindSnippet(input, string.Join(" ", new[] { "condimentum" }), 300, highlightSearchTerms ? "<b>" : "", highlightSearchTerms ? "</b>" : "");
	
	Console.WriteLine(summary);
}
```

The input is taken from the FullTextCache table.

**Comment by enkelmedia** [comment]
I can confirm this issue on the latest version (3.1.0). 

As @Nikkelmann mention the issue is in the Highlister.FindSnippet()-method. We can't assume that the exact search term is anywhere since it might be a fuzzy hit - in that case the searched term is nowhere to be found as an exact match.

I thinking that there are two possible solutions:

* Easy: If the highlighter returns a empty string, use the `input.TruncateHtml`
* Hard: Fix the Highlighter =D

@skttl Would you consider merging the easy fix? =D

**Comment by skttl** [comment]
If you'll do the fix, I'll merge 🙂

man. d. 19. jun. 2023 23.48 skrev Enkel Media ***@***.***>:
